name: car_rental_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  skeletonizer: ^2.0.1
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  lottie: ^3.3.1

  # dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0


  # Networking
  http: ^1.4.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4

  # Utils
  logging: ^1.3.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1
  intl: ^0.20.2

  # storage
  get_storage: ^2.1.1

  # maps and locations
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3

  flutter_gen_runner: any

flutter_gen:
  output: lib/generated/

  integrations:
#    flutter_svg: true
#    flare_flutter: true
#    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: ResAssets

#  fonts:
#    enabled: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/lottie/